server:
  port: 8095
spring:
  application:
    name: api-gateway-server
  cloud:
    config:
      enabled: true
    gateway:
      routes:
        # Service Two
        - id: service-one
          uri: lb://service-one
          predicates:
            - Path=/aplna/**
        # Service Two
        - id: service-two
          uri: lb://service-two
          predicates:
            - Path=/aplnb/**
eureka:
  instance:
    preferIpAddress: false
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#spring:
#  application:
#    name: gateway-service
#  cloud:
#    gateway:
#      routes:
#        - id: employeeModule
#          uri: lb://FIRST-SERVICE
#          predicates:
#            - Path=/employee/**
#        - id: consumerModule
#          uri: lb://SECOND-SERVICE
#          predicates:
#            - Path=/consumer/**
#zuul:
#  routes:
#    dynamic: true
#ribbon:
#  eureka:
#    enabled: true